{
 "title": "Invest Dashboard",
 "tags": [
  "bitcoin",
  "kraken",
  "ledger"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "tb_width",
    "label": "Time Bucket Width",
    "query": "1 second, 1 minute, 10 minutes, 1 hour, 12 hours, 1 day, "
   }
  ]
 },
 "panels": [
  { "title": "Quick Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Profilt in %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\ttime_bucket ('${tb_width}',\n\t\t\"time\") AS bucket_time,\n\t(avg(eur_on_kraken) + avg(eur_in_wallet)) / avg(total_cache_to_kraken) * 100 - 100 AS \"Profil 60m\"\nFROM\n\tinvestment_exporter\nWHERE\n\t$__timeFilter(time)\nGROUP BY\n\tbucket_time\nORDER BY\n\tbucket_time DESC"
    }
   ]
  },
  {
   "title": "Total investment",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket ('${tb_width}', \"time\") AS bucket_time,\n  avg(total_cache_to_kraken) AS \"Total Invest\"\nFROM\n  investment_exporter\nWHERE\n  $__timeFilter(time)\nGROUP BY\n  bucket_time\nORDER BY\n  bucket_time DESC"
    }
   ]
  },
  {
   "title": "Total value",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\ttime_bucket ('${tb_width}',\n\t\t\"time\") AS bucket_time,\n\t(avg(eur_on_kraken) + avg(eur_in_wallet)) AS \"Total Value\"\nFROM\n\tinvestment_exporter\nWHERE\n\t$__timeFilter(time)\nGROUP BY\n\tbucket_time\nORDER BY\n\tbucket_time DESC"
    }
   ]
  },
  {
   "title": "Bitcoin price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket ('${tb_width}', \"time\") AS bucket_time,\n  AVG(btc_price_usd) AS \"1 Day\"\nFROM\n  investment_exporter\nWHERE\n  $__timeFilter(time)\nGROUP BY\n  bucket_time\nORDER BY\n  bucket_time DESC"
    }
   ]
  },
  {
   "title": "Total Euro in Wallet",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT last(\"eur_in_wallet\", \"time\") FROM investment_exporter"
    }
   ]
  },
  {
   "title": "Total Euro at Kraken",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT last(\"eur_on_kraken\", \"time\") FROM investment_exporter"
    }
   ]
  },
  {
   "title": "Total BTC",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "₿" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT last(\"total_btc_on_kraken\", \"time\") + last(\"btc_in_wallet\", \"time\") FROM investment_exporter"
    }
   ]
  },
  {
   "title": "Tax-free BTC",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "₿" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE(SUM(amount), 0) AS btc FROM purchases WHERE time < NOW() - INTERVAL '1 year';"
    }
   ]
  },
  {
   "title": "Next DCA Order",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tTO_CHAR(AGE(LAST (\"next_dca_order_time\", \"time\"), NOW()), 'DD\"d\" HH24h MI') || 'm' AS last\nFROM\n\tinvestment_exporter"
    }
   ]
  },
  { "title": "Compared", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Profit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT\n\ttime_bucket ('${tb_width}',\n\t\t\"time\") AS bucket_time,\n\t(avg(eur_on_kraken) + avg(eur_in_wallet)) - avg(total_cache_to_kraken) AS \"Profit\"\nFROM\n\tinvestment_exporter\nWHERE\n\t$__timeFilter(time)\nGROUP BY\n\tbucket_time\nORDER BY\n\tbucket_time DESC"
    }
   ]
  },
  {
   "title": "Total Portfolio-Investment Map",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket ('${tb_width}', \"time\") AS bucket_time,\n  avg(eur_in_wallet) + avg(eur_on_kraken) AS \"Total Portfolio\"\nFROM\n  investment_exporter\nWHERE\n  $__timeFilter(time)\nGROUP BY\n  bucket_time\nORDER BY\n  bucket_time DESC"
    },
    {
     "rawSql": "SELECT\n  time_bucket ('${tb_width}', \"time\") AS bucket_time,\n  avg(total_cache_to_kraken) AS \"Total Investment\"\nFROM\n  investment_exporter\nWHERE\n  $__timeFilter(time)\nGROUP BY\n  bucket_time\nORDER BY\n  bucket_time DESC"
    }
   ]
  },
  {
   "title": "Portfolio overview",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT last(\"eur_in_wallet\", \"time\") AS \"Euro in Wallet\" FROM investment_exporter"
    },
    {
     "rawSql": "SELECT last(\"eur_on_kraken\", \"time\") AS \"Euro on Kraken\" FROM investment_exporter"
    }
   ]
  },
  {
   "title": "Monthly portfolio changes",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n\ttime_bucket ('1 month',\n\t\t\"time\") AS bucket_time,\n\tTO_CHAR(time_bucket ('1 month', \"time\"), 'Month') ||EXTRACT('Year' FROM time_bucket ('1 month', \"time\")) AS \"Date\",\n\t(avg(eur_on_kraken) + avg(eur_in_wallet)) / avg(total_cache_to_kraken) * 100 - 100 AS \"Change\",\n\t(min(eur_on_kraken) + min(eur_in_wallet)) / min(total_cache_to_kraken) * 100 - 100 AS \"Min Change\",\n\t(max(eur_on_kraken) + max(eur_in_wallet)) / max(total_cache_to_kraken) * 100 - 100 AS \"Max Change\"\nFROM\n\tinvestment_exporter\nGROUP BY\n\tbucket_time\nORDER BY\n\tbucket_time DESC"
    }
   ]
  },
  { "title": "Bitcoin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Bitcoin price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time_bucket ('${tb_width}', \"time\") AS bucket_time,\r\n  AVG(btc_price_usd) AS \"Bitcoin price\"\r\nFROM\r\n  investment_exporter\r\nWHERE\r\n  $__timeFilter(time)\r\nGROUP BY\r\n  bucket_time\r\nORDER BY\r\n  bucket_time DESC"
    }
   ]
  },
  {
   "title": "Bitcoin price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n\ttime_bucket ('12 hours',\n\t\t\"time\") AS bucket_time,\n    AVG(btc_price_usd) AS \"Bitcoin price\"\nFROM\n\tinvestment_exporter\nWHERE\n\t$__timeFilter(time)\nGROUP BY\n\tbucket_time\nORDER BY\n\tbucket_time DESC"
    }
   ]
  },
  { "title": "UTXO Management", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "UTXO Distribution",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH latest_balances AS (\n\tSELECT DISTINCT ON (address)\n\t\taddress,\n\t\ttime,\n\t\tbtc\n\tFROM\n\t\tutxo_balances\n\tORDER BY\n\t\taddress,\n\t\ttime DESC\n),\ntotal_balance AS (\n\tSELECT\n\t\tSUM(btc) AS total\n\tFROM\n\t\tlatest_balances\n)\nSELECT\n\tlb.address,\n\t(lb.btc / tb.total) * 100 AS Percentage\nFROM\n\tlatest_balances lb,\n\ttotal_balance tb\nORDER BY\n\tpercentage DESC;"
    }
   ]
  },
  { "title": "Invest Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "TimescaleDB Tables",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT\n  hypertable_name AS \"Hypertable Name\",\n  pg_size_pretty(\n    hypertable_approximate_size (\n      format('%I.%I', hypertable_schema, hypertable_name) :: regclass\n    )\n  ) AS \"Table Size\",\n  approximate_row_count (hypertable_name :: TEXT) AS \"Row Count\",\n  num_chunks AS \"Chunk Count\",\n  compression_enabled AS \"Compression Enabled\"\nFROM\n  timescaledb_information.hypertables"
    }
   ]
  },
  {
   "title": "Scrape Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket ('${tb_width}', \"time\") AS bucket_time,\n  AVG(total_scrape_time) AS \"Total Scrape Time\"\nFROM\n  investment_exporter\nWHERE\n  $__timeFilter(time)\nGROUP BY\n  bucket_time\nORDER BY\n  bucket_time DESC"
    }
   ]
  }
 ]
}